workspace 'pay.xcworkspace'

project 'PayClient/PayClient.xcodeproj'
 project 'MyLib/MyLib.xcodeproj'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/zoomyang/WTSpecs.git'

abstract_target 'Shows' do
    
    platform :ios, '8.0'
    
#    pod 'WebViewJavascriptBridge', '~> 5.0'  #html+IOS 混合编程
#    pod 'QRCodeReaderViewController', '~> 3.4.0'
    pod 'MBProgressHUD', '~> 0.8'
#    pod 'SDWebImage', '~> 3.7.1'
#    pod 'Toast', '~> 2.4' #提示
    #pod 'SVProgressHUD', '~> 1.1.2'
    #pod 'M80AttributedLabel', '~> 1.3.1'
#    pod 'FMDB', '~> 2.5'
    #pod 'FMDB/SQLCipher'
#    pod 'Reachability', '~> 3.1.1'
    #pod 'CocoaLumberjack', '~> 2.0.0-rc2'
    #pod 'SSZipArchive', '~> 1.2'
    #pod 'AFNetworking', '~> 2.0'
    # pod 'Objection', '1.6.1'
    pod 'MKNetworkKit', '0.87'
    pod 'MJRefresh', '> 0'
#    pod 'JSONModel', '>= 0'
#    pod 'PinYin4Objc', '>= 0'
#    pod 'MWPhotoBrowser', '>=0'
    pod 'GTMBase64', '>=0'
#    pod 'SBJson', '>=0'
#    pod 'OpenUDID', '~> 1.0.0'
    #pod 'Masonry'
    pod 'PureLayout'
    pod 'DZNEmptyDataSet'  #空状态模式 table为空的时候
#    pod 'MGSwipeTableCell' #可以滑动的 table cells 滑动后出现的按钮
    #pod 'XMLWriter'
    #pod 'XMLReader'
    pod 'NJKWebViewProgress' #UIWebView进度条管理  http://www.jianshu.com/p/318e774d82fe
    pod 'OpenSSL'
    pod 'UITableView+FDTemplateLayoutCell'
    # pod 'BaiduMapKit-JK', '~> 3.2.1'
    # pod 'BaiduNaviSDK-iOS-jk'
    # pod 'SS-BaiduPushSDK', '~> 1.4.5'
    # pod 'BaiduTraceSDK', '2.2.6'
    pod 'SGQRCode'
    pod 'Other' , '1.3'
    # pod 'PYSearch' #搜索页面及功能
    pod 'WKWebViewOC', '2.0'
#    pod 'RegexKitLite', '~> 4.0' #正则验证框架

    target 'MyLib' do
        project 'MyLib/MyLib.xcodeproj'
        

    end

    target 'PayClient' do
        
        
        pod 'ShareSDK3'
        pod 'MOBFoundation'
        pod 'ShareSDK3/ShareSDKUI'
        
        pod 'ShareSDK3/ShareSDKPlatforms/QQ'
#        pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
        pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
        
        pod 'ShareSDK3/ShareSDKExtension'
        
        
        project 'PayClient/PayClient.xcodeproj'
    end

end





